### ISSUE TITLE
How do I compile it?

### ISSUE THREAD

**Issue by mopoIo** [BranchofLight/CyTube-Room-Script#11]
How do I compile the src into the single .js file?
I want to make some changes with my own javascript but I don't know how to compile it back into the final file.
Thanks!

**Comment by BranchofLight** [comment]
It's been a while since I've built a new version and don't currently have my development computer.

But I imagine `webpack --mode=production` would work. Alternatively you could use the already setup `npm run webpack` however it won't compress the files.
